
Ext.app.AddDirPanel=function(){var path=Ext.app.StoreTree.getObj().getCurrentPath();var title='Add folder to '+path;Ext.app.AddDirPanel.superclass.constructor.call(this,{id:'AddDirPanel_Id',title:title,frame:true,bodyStyle:'padding: 10px 10px 0 10px;',labelWidth:50,defaults:{anchor:'95%',allowBlank:false,msgTarget:'side'},items:[{xtype:'hidden',hidden:true,name:'Path',value:path},{xtype:'textfield',fieldLabel:'Name',name:'Name'}],buttons:[{text:'Create',handler:function(){var form=Ext.getCmp('AddDirPanel_Id').getForm();if(form.isValid()){form.submit({url:'./ashx/addfolder.ashx',waitMsg:'Creating new folder...',success:function(sender,o){Ext.app.StoreTree.getObj().refresh();}});}}},{text:'Reset',handler:function(){var form=Ext.getCmp('AddDirPanel_Id').getForm();form.reset();}}]});};Ext.extend(Ext.app.AddDirPanel,Ext.FormPanel,{});
Ext.app.AddFilePanel=function(){var path=Ext.app.StoreTree.getObj().getCurrentPath();var title='Upload document to '+path;Ext.app.AddFilePanel.superclass.constructor.call(this,{id:'AddFilePanel_Id',title:title,fileUpload:true,frame:true,bodyStyle:'padding: 10px 10px 0 10px;',labelWidth:60,defaults:{anchor:'95%',allowBlank:false,msgTarget:'side'},items:[{xtype:'hidden',hidden:true,name:'Path',value:path},{xtype:'textfield',fieldLabel:'Name',name:'Name',},{xtype:'fileuploadfield',emptyText:'Select a document',fieldLabel:'Document',name:'File',buttonCfg:{text:'',iconCls:'upload-icon'}}],buttons:[{text:'Upload',handler:function(){var form=Ext.getCmp('AddFilePanel_Id').getForm();if(form.isValid()){form.submit({url:'./ashx/adddoc.ashx',waitMsg:'Uploading your document...',success:function(sender,o){Ext.app.StoreGrid.getObj().refresh();}});}}},{text:'Reset',handler:function(){var form=Ext.getCmp('AddFilePanel_Id').getForm();form.reset();}}]});};Ext.extend(Ext.app.AddFilePanel,Ext.FormPanel,{});
Ext.app.ContentPanel=function(){this.compId="";this.panelName="";this.actionButton=null;Ext.app.ContentPanel.superclass.constructor.call(this,{id:'ContentPanel_Id',layout:'fit',height:250,split:true,border:false,hidden:true,region:'south'});};Ext.extend(Ext.app.ContentPanel,Ext.Panel,{clear:function(){this.remove(this.compId);this.compId=null;this.panelName="";this.actionButton=null;this.hide();this.ownerCt.doLayout();if(this.actionButton!=null)
{this.actionButton.toggle(true);}},showPanel:function(panelName,actionButton){this.remove(this.compId);if(this.panelName==panelName)
{this.compId=null;this.panelName="";this.actionButton=null;this.hide();this.ownerCt.doLayout();return;}
else if(this.actionButton!=null)
{this.actionButton.toggle(false);}
var comp=null;if(panelName=="AddDir")
comp=this.add(new Ext.app.AddDirPanel());else if(panelName=="AddFile")
comp=this.add(new Ext.app.AddFilePanel());else
{this.panelName="";return;}
this.compId=comp.id;this.panelName=panelName;this.actionButton=actionButton;this.show();this.ownerCt.doLayout();}});
Ext.form.FileUploadField=Ext.extend(Ext.form.TextField,{buttonText:'Browse...',buttonOnly:false,buttonOffset:3,readOnly:true,autoSize:Ext.emptyFn,initComponent:function(){Ext.form.FileUploadField.superclass.initComponent.call(this);this.addEvents('fileselected');},onRender:function(ct,position){Ext.form.FileUploadField.superclass.onRender.call(this,ct,position);this.wrap=this.el.wrap({cls:'x-form-field-wrap x-form-file-wrap'});this.el.addClass('x-form-file-text');this.el.dom.removeAttribute('name');this.fileInput=this.wrap.createChild({id:this.getFileInputId(),name:this.name||this.getId(),cls:'x-form-file',tag:'input',type:'file',size:1});var btnCfg=Ext.applyIf(this.buttonCfg||{},{text:this.buttonText});this.button=new Ext.Button(Ext.apply(btnCfg,{renderTo:this.wrap,cls:'x-form-file-btn'+(btnCfg.iconCls?' x-btn-icon':'')}));if(this.buttonOnly){this.el.hide();this.wrap.setWidth(this.button.getEl().getWidth());}
this.fileInput.on('change',function(){var v=this.fileInput.dom.value;this.setValue(v);this.fireEvent('fileselected',this,v);},this);},getFileInputId:function(){return this.id+'-file';},onResize:function(w,h){Ext.form.FileUploadField.superclass.onResize.call(this,w,h);this.wrap.setWidth(w);if(!this.buttonOnly){var w=this.wrap.getWidth()-this.button.getEl().getWidth()-this.buttonOffset;this.el.setWidth(w);}},preFocus:Ext.emptyFn,getResizeEl:function(){return this.wrap;},getPositionEl:function(){return this.wrap;},alignErrorIcon:function(){this.errorIcon.alignTo(this.wrap,'tl-tr',[2,0]);}});Ext.reg('fileuploadfield',Ext.form.FileUploadField);
Ext.app.LoginPanel=function(){Ext.app.LoginPanel.superclass.constructor.call(this,{id:'LoginPanel_Id',layout:'table',border:false,autoheight:true,layoutConfig:{columns:2},items:[{xtype:'textfield',hideLabel:true,emptyText:'Input your e-mail for login',name:'email',width:200},new Ext.Button({text:'Login',handler:this.onLogin,scope:this})],keys:[{key:Ext.EventObject.ENTER,fn:this.onLogin,scope:this}]});};Ext.extend(Ext.app.LoginPanel,Ext.FormPanel,{onLogin:function(){var form=this.getForm();if(form.isValid()){form.submit({url:'./ashx/login.ashx',waitMsg:'Login ...',success:function(sender,o){this.updateState(o.result.data);},scope:this});}},updateState:function(o){Ext.app.UserState=o;Ext.app.MainPanel.getObj().updateToolbar(o);}});Ext.app.UserState=null;
Ext.app.MainPanel=function(){this.grid=new Ext.app.StoreGrid();Ext.app.MainPanel.superclass.constructor.call(this,{id:'MainPanel_Id',region:'center',margins:'3 3 3 0',layout:'border',defaults:{autoScroll:true},tbar:new Ext.Toolbar([new Ext.Action({id:"btn_addDir",text:'Add folder',disabled:true,tooltip:{title:'Add folder',text:'Add sub folder to current path.'},enableToggle:true,handler:this.onAddDir,scope:this}),'-',new Ext.Action({id:"btn_addFile",text:'Add Document',disabled:true,tooltip:{title:'Add Document',text:'Upload document to current folder.'},enableToggle:true,handler:this.onAddFile,scope:this})]),items:[this.grid,new Ext.app.ContentPanel()]});};Ext.extend(Ext.app.MainPanel,Ext.Panel,{updateToolButton:function(o,action){if(o.disabled!=null){action.setDisabled(o.disabled);}},updateToolbar:function(o){if(o.addDir!=null){this.updateToolButton(o.addDir,Ext.getCmp('btn_addDir'));}
if(o.addFile!=null){this.updateToolButton(o.addFile,Ext.getCmp('btn_addFile'));}},onAddDir:function(item){var bot=Ext.getCmp('ContentPanel_Id');bot.showPanel("AddDir",Ext.getCmp('btn_addDir'));},onAddFile:function(item){var bot=Ext.getCmp('ContentPanel_Id');bot.showPanel("AddFile",Ext.getCmp('btn_addFile'));}});Ext.app.MainPanel.getObj=function(){return Ext.getCmp('MainPanel_Id');};
function onTimer(){var msg=Ext.getCmp("message-panel");msg.onTimer();};Ext.app.MessagePanel=function(){this.label=new Ext.form.Label();this.sec=0;Ext.app.MessagePanel.superclass.constructor.call(this,{id:'message-panel',width:300,height:30,split:true,border:false});this.add(this.label);};Ext.extend(Ext.app.MessagePanel,Ext.Panel,{showMessage:function(msg,err,sec){if(msg==null||msg=="")
return;if(err==null)
err=false;if(sec==null)
sec=3000;this.label.setText(msg);setTimeout(function(){onTimer();},sec);},onTimer:function(){this.label.setText("");}});
Ext.grid.RowExpander=function(config){Ext.apply(this,config);this.addEvents({beforeexpand:true,expand:true,beforecollapse:true,collapse:true});Ext.grid.RowExpander.superclass.constructor.call(this);if(this.tpl){if(typeof this.tpl=='string'){this.tpl=new Ext.Template(this.tpl);}
this.tpl.compile();}
this.state={};this.bodyContent={};};Ext.extend(Ext.grid.RowExpander,Ext.util.Observable,{header:"",width:20,sortable:false,fixed:true,menuDisabled:true,dataIndex:'',id:'expander',lazyRender:true,enableCaching:true,getRowClass:function(record,rowIndex,p,ds){p.cols=p.cols-1;var content=this.bodyContent[record.id];if(!content&&!this.lazyRender){content=this.getBodyContent(record,rowIndex);}
if(content){p.body=content;}
return this.state[record.id]?'x-grid3-row-expanded':'x-grid3-row-collapsed';},init:function(grid){this.grid=grid;var view=grid.getView();view.getRowClass=this.getRowClass.createDelegate(this);view.enableRowBody=true;grid.on('render',function(){view.mainBody.on('mousedown',this.onMouseDown,this);},this);},getBodyContent:function(record,index){if(!this.enableCaching){return this.tpl.apply(record.data);}
var content=this.bodyContent[record.id];if(!content){content=this.tpl.apply(record.data);this.bodyContent[record.id]=content;}
return content;},onMouseDown:function(e,t){if(t.className=='x-grid3-row-expander'){e.stopEvent();var row=e.getTarget('.x-grid3-row');this.toggleRow(row);}},renderer:function(v,p,record){p.cellAttr='rowspan="2"';return'<div class="x-grid3-row-expander">&#160;</div>';},beforeExpand:function(record,body,rowIndex){if(this.fireEvent('beforeexpand',this,record,body,rowIndex)!==false){if(this.tpl&&this.lazyRender){body.innerHTML=this.getBodyContent(record,rowIndex);}
return true;}else{return false;}},toggleRow:function(row){if(typeof row=='number'){row=this.grid.view.getRow(row);}
this[Ext.fly(row).hasClass('x-grid3-row-collapsed')?'expandRow':'collapseRow'](row);},expandRow:function(row){if(typeof row=='number'){row=this.grid.view.getRow(row);}
var record=this.grid.store.getAt(row.rowIndex);var body=Ext.DomQuery.selectNode('tr:nth(2) div.x-grid3-row-body',row);if(this.beforeExpand(record,body,row.rowIndex)){this.state[record.id]=true;Ext.fly(row).replaceClass('x-grid3-row-collapsed','x-grid3-row-expanded');this.fireEvent('expand',this,record,body,row.rowIndex);}},collapseRow:function(row){if(typeof row=='number'){row=this.grid.view.getRow(row);}
var record=this.grid.store.getAt(row.rowIndex);var body=Ext.fly(row).child('tr:nth(1) div.x-grid3-row-body',true);if(this.fireEvent('beforecollapse',this,record,body,row.rowIndex)!==false){this.state[record.id]=false;Ext.fly(row).replaceClass('x-grid3-row-expanded','x-grid3-row-collapsed');this.fireEvent('collapse',this,record,body,row.rowIndex);}}});
Ext.state.SessionProvider=Ext.extend(Ext.state.CookieProvider,{readCookies:function(){if(this.state){for(var k in this.state){if(typeof this.state[k]=='string'){this.state[k]=this.decodeValue(this.state[k]);}}}
return Ext.apply(this.state||{},Ext.state.SessionProvider.superclass.readCookies.call(this));}});
Ext.app.StorePanel=function(){this.tree=new Ext.app.StoreTree();this.main=new Ext.app.MainPanel();Ext.app.StorePanel.superclass.constructor.call(this,{id:'StorePanel_Id',height:400,autoWidth:true,plain:true,layout:'border',items:[this.tree,this.main]});this.tree.on('click',this.onSelectTreeNode,this);this.onSelectTreeNode(this.tree.root);};Ext.extend(Ext.app.StorePanel,Ext.Panel,{onSelectTreeNode:function(node){this.main.grid.load(node.getPath());},getStatusbar:function(){return Ext.getCmp('Statusbar_Id');}});Ext.app.StorePanel.getObj=function(){return Ext.getCmp('StorePanel_Id');};Ext.BLANK_IMAGE_URL='../extjs/resources/images/default/s.gif';Ext.onReady(function(){Ext.QuickTips.init();Ext.state.Manager.setProvider(new Ext.state.SessionProvider({state:Ext.appState}));new Ext.StatusBar({id:'Statusbar_Id',hidden:true,defaultText:'Ready'}).render('msgbox');new Ext.app.LoginPanel().render('loginbox');var panel=new Ext.app.StorePanel();panel.render('view');var resizer=new Ext.Resizable(panel.getEl(),{width:panel.width,height:panel.height,minHeight:200,handles:'s',heightIncrement:5,dynamic:true});resizer.on('resize',function(){panel.updateBox(panel.getSize());});});
Ext.app.StoreGrid=function(){var expander=new Ext.grid.RowExpander({tpl:new Ext.Template('<p><b>Company:</b> {name}</p><br>','<p><b>Summary:</b> {time}</p>')});Ext.app.StoreGrid.superclass.constructor.call(this,{id:'StoreGrid_Id',store:new Ext.data.Store({reader:new Ext.app.StoreGridReader()}),columns:[expander,{header:"Name",width:160,sortable:true,dataIndex:'name'},{header:"Size",width:75,sortable:true,renderer:this.formatSize,dataIndex:'size',align:'right'},{header:"Upload time",width:85,sortable:true,dataIndex:'time'}],stripeRows:true,border:false,plugins:expander,region:'center'});};Ext.extend(Ext.app.StoreGrid,Ext.grid.GridPanel,{load:function(path){var url="."+path+"/docs.xml";var conn=new Ext.data.Connection({url:url});this.store.proxy=new Ext.data.HttpProxy(conn);this.store.proxy.on('loadexception',this.onLoadException,this);this.store.reload();},onLoadException:function(o,options,response,e){this.store.removeAll();},formatSize:function(size){return Ext.util.Format.fileSize(size);},refresh:function(){this.load(Ext.app.StoreTree.getObj().getCurrentPath());}});Ext.app.StoreGrid.getObj=function(){return Ext.getCmp('StoreGrid_Id');};
Ext.app.StoreGridReader=function(){var meta={};var recordType=[{name:'name'},{name:'size'},{name:'time'}];Ext.app.StoreGridReader.superclass.constructor.call(this,meta,recordType);};Ext.extend(Ext.app.StoreGridReader,Ext.data.XmlReader,{readRecords:function(doc){var root=doc.documentElement||doc;var recordType=this.recordType,fields=recordType.prototype.fields;var totalRecords=0,success=true;var records=[];var ns=Ext.DomQuery.select("doc",root);for(var i=0,len=ns.length;i<len;i++){var n=ns[i];var values={};for(var j=0,jlen=fields.length;j<jlen;j++){var f=fields.items[j];values[f.name]=n.getAttribute(f.name);}
var record=new recordType(values,null);record.node=n;records[records.length]=record;}
return{success:success,records:records,totalRecords:totalRecords||records.length};}});
Ext.app.StoreTree=function(){Ext.app.StoreTree.superclass.constructor.call(this,{id:'StoreTree_Id',title:'Folders',region:'west',split:true,useArrows:true,animate:true,width:200,collapsible:true,margins:'3 0 3 3',cmargins:'3 3 3 3',autoScroll:true,loader:new Ext.app.StoreTreeLoader({clearOnLoad:false}),root:new Ext.tree.AsyncTreeNode({id:'root',text:'Store'})});this.root.expand();};Ext.extend(Ext.app.StoreTree,Ext.tree.TreePanel,{getCurrentPath:function(){var node=this.getSelectionModel().getSelectedNode();if(!node)
node=this.root;return node.getPath();},refresh:function(){var node=this.getSelectionModel().getSelectedNode();if(!node)
node=this.root;node.reload();}});Ext.app.StoreTree.getObj=function(){return Ext.getCmp('StoreTree_Id');};
Ext.app.StoreTreeLoader=Ext.extend(Ext.tree.TreeLoader,{load:function(node,callback){if(this.clearOnLoad){while(node.firstChild){node.removeChild(node.firstChild);}}
if(this.doPreload(node)){if(typeof callback=="function"){callback();}}else if(node.attributes){this.requestData(node,callback);}},requestData:function(node,callback){if(this.fireEvent("beforeload",this,node,callback)!==false){var url="."+node.getPath()+"/dirs.xml";this.transId=Ext.Ajax.request({method:'GET',url:url,success:this.handleResponse,failure:this.handleFailure,scope:this,argument:{callback:callback,node:node},params:this.getParams(node)});}else{if(typeof callback=="function"){callback();}}},createNode:function(nodeDir){var name=nodeDir.getAttribute("name");return new Ext.tree.AsyncTreeNode({id:name,text:name});},processResponse:function(response,node,callback){var doc=response.responseXML;try{var root=doc.documentElement||doc;var dirs=Ext.DomQuery.select("dir",root);node.beginUpdate();for(var i=0;i<dirs.length;i++)
{var n=this.createNode(dirs[i]);if(n)
node.appendChild(n);}
node.endUpdate();if(typeof callback=="function"){callback(this,node);}}catch(e){this.handleFailure(response);}},handleFailure:function(response){this.transId=false;var a=response.argument;this.fireEvent("loadexception",this,a.node,response);if(typeof a.callback=="function"){a.callback(this,a.node);}}});